name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: install-deps
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip gcc pkg-config libsdl2-dev wget ninja-build libcodec2-dev codec2 git libreadline-dev libusb-1.0-0-dev cmake g++ dfu-util meson
        wget -O /tmp/MiosixToolchainInstaller.run https://miosix.org/toolchain/MiosixToolchainInstaller.run
        sudo sh /tmp/MiosixToolchainInstaller.run
    - name: build-radio-tool
      run: |
        cd ${{github.workspace}}
        git clone https://github.com/v0l/radio_tool build_radio_tool
        cmake -S build_radio_tool -B build_radio_tool -Wno-dev
        cmake --build build_radio_tool --parallel 8
        cp build_radio_tool/radio_tool .
    - name: meson-setup
      run: |
        cd ${{github.workspace}}
        meson setup build_linux
        meson setup --cross-file cross_arm.txt build_arm
    - name: ninja
      run: |
        cd ${{github.workspace}}
        ninja -C build_linux openrtx_linux -j4
        ninja -C build_arm openrtx_md3x0_wrap -j4
        ninja -C build_arm openrtx_mduv3x0_wrap -j4
        ninja -C build_arm openrtx_gd77_bin -j4
        ninja -C build_arm openrtx_dm1801_bin -j4

