name: "Run unit tests"
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: install-deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip gcc pkg-config libsdl2-dev wget ninja-build libcodec2-dev codec2 git libreadline-dev libusb-1.0-0-dev cmake g++ dfu-util meson
      - name: build-radio-tool
        run: |
          cd ${{github.workspace}}
          git clone https://github.com/v0l/radio_tool build_radio_tool
          cmake -S build_radio_tool -B build_radio_tool -Wno-dev
          cmake --build build_radio_tool --parallel 8
          cp build_radio_tool/radio_tool .
      - name: setup meson
        run: |
          cd ${{github.workspace}}
          meson setup build
      - name: M17 Viterbi Unit Test
        run: meson test -C build "M17 Viterbi Unit Test"
      - name: M17 Golay Unit Test
        run: meson test -C build "M17 Golay Unit Test"
      - name: M17 RRC Test
        run: meson test -C build "M17 RRC Test"
      - name: Codeplug Test
        run: meson test -C build "Codeplug Test"
      # The following tests are disabled because they appear to be flakey when run in CI
      # - name: Sine Test
      #   run: meson test -C build "Sine Test"
      # - name: Linux InputStream Test
      #   run: meson test -C build "Linux InputStream Test"
